version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    # command: [ "./wait-for-it.sh", "database:3306", "--timeout=50", "--", "npm", "start" ]
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"