pipeline {
    agent {
        kubernetes {
            cloud 'kubernetes'
        }
    }
 

    stages {
        stage('version') {
            steps {
                node('node') {
                    sh 'node -v'
                    sh 'ls'
                }
            }            
        }
    }
}