pipeline {
    agent {
        kubernetes {
            cloud 'kubernetes'
        }
    }
 

    stages {
        stage('version') {
            node('node') {
                steps {
                    sh 'node -v'
                }
                steps {
                    sh 'ls'
                }
            }
        }
    }
}