---
- name: Update Repository
  apt: update_cache=true
  become: yes

- name: Install Docker Dependencies
  apt: 
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Check linux release
  block:
    - name: release
      command: lsb_release -cs
      register: release

    - name: architecture
      command: dpkg --print-architecture
      register: arch

- name: Add Docker GPG Key
  get_url: 
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg

- name: Add Docker repo
  apt_repository: 
    repo: deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ release.stdout }} stable
    state: present

- name: Update Repository
  apt: update_cache=true
  become: yes

- name: Install Docker
  apt:
    name: docker-ce docker-ce-cli containerd.io docker-compose-plugin
  notify:
    - start docker

- name: Add Jenkins to Docker Group
  ansible.builtin.user:
    name: jenkins
    group: docker