---
- name: Update Repository
  apt: update_cache=true
  become: yes

- name: Get docker script
  get_url: 
    url: https://get.docker.com
    dest: get-docker.sh

- name: Install docker script
  command: sh ./get-docker.sh

- name: Add Jenkins to Docker Group
  ansible.builtin.user:
    name: jenkins
    group: docker