---
- name: Update Repository
  apt: update_cache=true
  become: yes

- name: Download kubectl
  command: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

- name: Install kubectl
  command: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  become: yes

- name: Initialize Cluster with kOps
  shell: setup.sh
  args:
    chdir: ../../../../kops/